### PR TITLE
Dan/3d octahedron

### PR DESCRIPTION
**Pull request by danielkwalsh**
- Grapher file removed
- Octahedron now spins in a random direction for a while, switching axes periodically to keep things interesting.
- Octahedron radius  "ballradius" can be changed. Set ballradius to a large number to illluminate the entire tree!
- colourA through colourH can be modified to create a personalized holiday spirit!

### CODE REVIEW

**Comment by danielkwalsh** [comment]
@oliverdunk Hey Oliver. Take a look at my new PR. I moved my example into the "examples" directory. I've only been able to test it with the simulator, so I'd be very interested to see how this looks in real life. Eager to continue coming up with improvements here! Please keep me updated.

Dan

**Comment by oliverdunk** [comment]
Hey again @danielkwalsh! This looks great, but I think Matt's original code has been accidentally removed in it? Appreciate your time on this, if you can fix that I think it's good to merge. Let me know if you need any help figuring it out.

**Comment by danielkwalsh** [comment]
Hey, Oliver. Sorry about that. I must have accidentally deleted the file. I've replaced Matt's file again so now there should be no problems merging this PR.

**Comment by danielkwalsh** [comment]
Hey @oliverdunk, just checking in again to see what's blocking merging this PR. Is there anything else you need?

**Comment by oliverdunk** [comment]
Hey @danielkwalsh - nothing blocking this! Let's get it merged, thanks for tweaking it slightly :)

**Pull request merged**
