### PR TITLE
Preview mode for the script

### PR DESCRIPTION
**Pull request by hybrist**
This is super hacky but I thought it might become handy for some people: A way to preview the result of the script, at least roughly. Currently only tested with the example script in the repo. No fancy camera controls or light effects. But it allows editing the Python script, reloading the page, and seeing it in action.

Live demo: https://jkrems.dev/xmastree2020/preview/

### CODE REVIEW

**Comment by thomas-davignon** [comment]
Hi I followed the link, but I can't edit the script... :(

**Comment by mreithub** [comment]
Hi, I've been working on something similar - but wanted a fully web-based way for users to edit things (similar to jsfiddle) and found trinket.io.
Feel free to steal some of my code (e.g the matrix rotation stuff etc):

https://trinket.io/python/61921f843e 

I've only gotten as far as to draw the dot cloud as well as do some simple matrix rotations
(I've run out of time for today so I'll post this here as-is).

current status:
- quick'n'dirty snapshot (I hope the code is somewhat readable)
- Tree class stores the dot cloud (each dot is a Vector3d instance)
- Tree().rotate(zangle=123) returns the dot cloud after rotating it by zangle degrees around the z-axis
  TODO maybe return a new, rotated Tree instance instead (to allow method chaining)
- I've tried to run the drawTree() method repeatedly (also calling screen.clearscreen()) but it doesn't work for some reason
  and I've run out of time to investigate further :)
  haven't worked with the turtle lib yet (and I'm kinda abusing it - a lower level drawing lib would be sufficient, but turtle is what's supported on this site and is easy to use)
- re-running things causes flickering (so you can't really see the animation unless you focus on single dots on the edge of the tree)
- everything in helpercode.py only relies on builtin python3 stuff and should be reusable
- the "turtle" is still visible - this should be fixable
- if you disable the turtle.on() and .off() calls, you can see the lines - i.e. the 'wiring' of the led strips
  (assuming their addressing matches their position on the led strip)
  this also makes it easier to see the rotation
- no colors yet - I was planning on doing the tree display and rotation first (i.e. the TreeSimulator™️ :) ) and only add a simple animation, share the link and let users play with it and try out their own animations

**Note:** I'm looking for input but don't wanna hijack the conversation in this pull request - I'll maybe open an issue later to have a separate thread if people are interested.  
Just wanted to post this here in case @jkrems finds some code they wanna include in their solution ;)

**Comment by hybrist** [comment]
> Hi I followed the link, but I can't edit the script... :(

Sorry for the confusion there. Right now the text on the site isn't editable but the way to try out changes would be:

1. Clone the repo.
1. Run `python3 -m http.server 8000` in the checkout directory.
1. Open http://localhost:3000/preview.
1. Change `xmaslights-spin.py` and reload the browser.

Pretty manual but it kind of works (and at least faster than to wait for Matt to run it on a real tree).

I didn't have time to make live editing in the browser work last night, so I just added a `readonly` to the `<textarea>` to reduce the confusion a little bit.

> Hi, I've been working on something similar - but wanted a fully web-based way for users to edit things (similar to jsfiddle) and found trinket.io.

Thanks for sharing, @mreithub! That looks pretty neat. I think in the background both solutions use the same "guts" (`Skulpt`). I had briefly looked at trinket as the editing solution but I couldn't (quickly) find a way to render the 3D tree or plug a trinket into custom runtime code. And without the custom runtime, it seemed hard to make the real tree scripts work 1:1 in the browser. But I think having an at least partially copy&paste-able, simpler fiddle would be awesome!

**Comment by hybrist** [comment]
Pushed some cleanup:

1. It's now possible to edit the script in the browser.
2. When editing, it updates the `#` fragment in the URL to contain the script source. The resulting URL should be somewhat sharable.
3. To see the result of an edit reflected in the render, it's necessary to click `▶`.
4. There's no a checkbox to rotate the rendered tree to see it from other directions. It's a poor replacement for mouse camera control but it's a start.

[Example link for a slight color change](https://jkrems.dev/xmastree2020/preview/#ZGVmIHhtYXNsaWdodCgpOgogICAgIyBUaGlzIGlzIHRoZSBjb2RlIGZyb20gbXkKCiAgICAjTk9URSBUSEUgTEVEUyBBUkUgR1JCIENPTE9VUiAoTk9UIFJHQikKCiAgICAjIEhlcmUgYXJlIHRoZSBsaWJyYXJpZXMgSSBhbSBjdXJyZW50bHkgdXNpbmc6CiAgICBpbXBvcnQgdGltZQogICAgaW1wb3J0IGJvYXJkCiAgICBpbXBvcnQgbmVvcGl4ZWwKICAgIGltcG9ydCByZQogICAgaW1wb3J0IG1hdGgKCiAgICAjIFlvdSBhcmUgd2VsY29tZSB0byBhZGQgYW55IG9mIHRoZXNlOgogICAgIyBpbXBvcnQgcmFuZG9tCiAgICAjIGltcG9ydCBudW1weQogICAgIyBpbXBvcnQgc2NpcHkKICAgICMgaW1wb3J0IHN5cwoKICAgICMgSWYgeW91IHdhbnQgdG8gaGF2ZSB1c2VyIGNoYW5nYWJsZSB2YWx1ZXMsIHRoZXkgbmVlZCB0byBiZSBlbnRlcmVkIGZyb20gdGhlIGNvbW1hbmQgbGluZQogICAgIyBzbyBpbXBvcnQgc3lzIHN5cyBhbmQgdXNlIHN5cy5hcmd2WzBdIGV0YwogICAgIyBzb21lX3ZhbHVlID0gaW50KHN5cy5hcmd2WzBdKQoKICAgICMgSU1QT1JUIFRIRSBDT09SRElOQVRFUyAocGxlYXNlIGRvbid0IGJyZWFrIHRoaXMgYml0KQoKICAgIGNvb3JkZmlsZW5hbWUgPSAiUHl0aG9uL2Nvb3Jkcy50eHQiCgogICAgZmluID0gb3Blbihjb29yZGZpbGVuYW1lLCdyJykKICAgIGNvb3Jkc19yYXcgPSBmaW4ucmVhZGxpbmVzKCkKCiAgICBjb29yZHNfYml0cyA9IFtpLnNwbGl0KCIsIikgZm9yIGkgaW4gY29vcmRzX3Jhd10KCiAgICBjb29yZHMgPSBbXQoKICAgIGZvciBzbGFiIGluIGNvb3Jkc19iaXRzOgogICAgICAgIG5ld19jb29yZCA9IFtdCiAgICAgICAgZm9yIGkgaW4gc2xhYjoKICAgICAgICAgICAgbmV3X2Nvb3JkLmFwcGVuZChpbnQocmUuc3ViKHInW14tXGRdJywnJywgaSkpKQogICAgICAgIGNvb3Jkcy5hcHBlbmQobmV3X2Nvb3JkKQoKICAgICNzZXQgdXAgdGhlIHBpeGVscyAoQUtBICdMRURzJykKICAgIFBJWEVMX0NPVU5UID0gbGVuKGNvb3JkcykgIyB0aGlzIHNob3VsZCBiZSA1MDAKCiAgICBwaXhlbHMgPSBuZW9waXhlbC5OZW9QaXhlbChib2FyZC5EMTgsIFBJWEVMX0NPVU5ULCBhdXRvX3dyaXRlPUZhbHNlKQoKCiAgICAjIFlPVSBDQU4gRURJVCBGUk9NIEhFUkUgRE9XTgoKICAgICMgSSBnZXQgYSBsaXN0IG9mIHRoZSBoZWlnaHRzIHdoaWNoIGlzIG5vdCBvdmVybHkgdXNlZnVsIGhlcmUgb3RoZXIgdGhhbiB0byBzZXQgdGhlIG1heCBhbmQgbWluIGFsdGl0dWRlcwogICAgaGVpZ2h0cyA9IFtdCiAgICBmb3IgaSBpbiBjb29yZHM6CiAgICAgICAgaGVpZ2h0cy5hcHBlbmQoaVsyXSkKCiAgICBtaW5fYWx0ID0gbWluKGhlaWdodHMpCiAgICBtYXhfYWx0ID0gbWF4KGhlaWdodHMpCgogICAgIyBWQVJJT1VTIFNFVFRJTkdTCgogICAgIyBob3cgbXVjaCB0aGUgcm90YXRpb24gcG9pbnRzIG1vdmVzIGVhY2ggdGltZQogICAgZGluYyA9IDEKCiAgICAjIGEgYnVmZmVyIHNvIGl0IGRvZXMgbm90IGhpdCB0byBleHRyZW1lIHRvcCBvciBib3R0b20gb2YgdGhlIHRyZWUKICAgIGJ1ZmZlciA9IDIwMAoKICAgICMgcGF1c2UgYmV0d2VlbiBjeWNsZXMgKG5vcm1hbGx5IHplcm8gYXMgaXQgaXMgYWxyZWFkeSBxdWl0ZSBzbG93KQogICAgc2xvdyA9IDAKCiAgICAjIHN0YXJ0aW4gYW5nbGUgKGluIHJhZGlhbnMpCiAgICBhbmdsZSA9IDAKCiAgICAjIGhvdyBtdWNoIHRoZSBhbmdsZSBjaGFuZ2VzIHBlciBjeWNsZQogICAgaW5jID0gMC4xCgogICAgIyB0aGUgdHdvIGNvbG91cnMgaW4gR1JCIG9yZGVyCiAgICAjIGlmIHlvdSBhcmUgdHVybmluZyBhIGxvdCBvZiB0aGVtIG9uIGF0IG9uY2UsIGtlZXAgdGhlaXIgYnJpZ2h0bmVzcyBkb3duIHBsZWFzZQogICAgY29sb3VyQSA9IFswLDc1LDBdICMgcmVkCiAgICBjb2xvdXJCID0gWzc1LDAsMF0gIyBncmVlbgoKCiAgICAjIElOSVRJQUxJU0UgU09NRSBWQUxVRVMKCiAgICBzd2FwMDEgPSAwCiAgICBzd2FwMDIgPSAwCgogICAgIyBkaXJlY3QgaXQgbW92ZSBpbgogICAgZGlyZWN0aW9uID0gLTEKCiAgICAjIHRoZSBzdGFydGluZyBwb2ludCBvbiB0aGUgdmVydGljYWwgYXhpcwogICAgYyA9IDEwMAoKICAgICMgeWVzLCBJIGp1c3QgcnVuIHdoaWNoIHJ1biBpcyB0cnVlCiAgICBydW4gPSAxCiAgICB3aGlsZSBydW4gPT0gMToKCiAgICAgICAgdGltZS5zbGVlcChzbG93KQoKICAgICAgICBMRUQgPSAwCiAgICAgICAgd2hpbGUgTEVEIDwgbGVuKGNvb3Jkcyk6CiAgICAgICAgICAgIGlmIG1hdGgudGFuKGFuZ2xlKSpjb29yZHNbTEVEXVsxXSA8PSBjb29yZHNbTEVEXVsyXStjOgogICAgICAgICAgICAgICAgcGl4ZWxzW0xFRF0gPSBjb2xvdXJBCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBwaXhlbHNbTEVEXSA9IGNvbG91ckIKICAgICAgICAgICAgTEVEICs9IDEKCiAgICAgICAgIyB1c2UgdGhlIHNob3coKSBvcHRpb24gYXMgcmFyZWx5IGFzIHBvc3NpYmxlIGFzIGl0IHRha2VzIGFnZXMKICAgICAgICAjIGRvIG5vdCB1c2Ugc2hvdygpIGVhY2ggdGltZSB5b3UgY2hhbmdlIGEgTEVEIGJ1dCByYXRoZXIgd2FpdCB1bnRpbCB5b3UgaGF2ZSBjaGFuZ2VkIHRoZW0gYWxsCiAgICAgICAgcGl4ZWxzLnNob3coKQoKICAgICAgICAjIG5vdyB3ZSBnZXQgcmVhZHkgZm9yIHRoZSBuZXh0IGN5Y2xlCgogICAgICAgIGFuZ2xlICs9IGluYwogICAgICAgIGlmIGFuZ2xlID4gMiptYXRoLnBpOgogICAgICAgICAgICBhbmdsZSAtPSAyKm1hdGgucGkKICAgICAgICAgICAgc3dhcDAxID0gMAogICAgICAgICAgICBzd2FwMDIgPSAwCgogICAgICAgICMgdGhpcyBpcyBhbGwgdG8ga2VlcCB0cmFjayBvZiB3aGljaCBjb2xvdXIgaXMgJ29uIHRvcCcKCiAgICAgICAgaWYgYW5nbGUgPj0gMC41Km1hdGgucGk6CiAgICAgICAgICAgIGlmIHN3YXAwMSA9PSAwOgogICAgICAgICAgICAgICAgY29sb3VyX2hvbGQgPSBbaSBmb3IgaSBpbiBjb2xvdXJBXQogICAgICAgICAgICAgICAgY29sb3VyQSA9W2kgZm9yIGkgaW4gY29sb3VyQl0KICAgICAgICAgICAgICAgIGNvbG91ckIgPSBbaSBmb3IgaSBpbiBjb2xvdXJfaG9sZF0KICAgICAgICAgICAgICAgIHN3YXAwMSA9IDEKCiAgICAgICAgaWYgYW5nbGUgPj0gMS41Km1hdGgucGk6CiAgICAgICAgICAgIGlmIHN3YXAwMiA9PSAwOgogICAgICAgICAgICAgICAgY29sb3VyX2hvbGQgPSBbaSBmb3IgaSBpbiBjb2xvdXJBXQogICAgICAgICAgICAgICAgY29sb3VyQSA9W2kgZm9yIGkgaW4gY29sb3VyQl0KICAgICAgICAgICAgICAgIGNvbG91ckIgPSBbaSBmb3IgaSBpbiBjb2xvdXJfaG9sZF0KICAgICAgICAgICAgICAgIHN3YXAwMiA9IDEKCiAgICAgICAgIyBhbmQgd2UgbW92ZSB0aGUgcm90YXRpb24gcG9pbnQKICAgICAgICBjICs9IGRpcmVjdGlvbipkaW5jCgogICAgICAgIGlmIGMgPD0gbWluX2FsdCtidWZmZXI6CiAgICAgICAgICAgIGRpcmVjdGlvbiA9IDEKICAgICAgICBpZiBjID49IG1heF9hbHQtYnVmZmVyOgogICAgICAgICAgICBkaXJlY3Rpb24gPSAtMQoKICAgIHJldHVybiAnRE9ORScKCgojIHllcywgSSBqdXN0IHB1dCB0aGlzIGF0IHRoZSBib3R0b20gc28gaXQgYXV0byBydW5zCnhtYXNsaWdodCgpCgo=)

**Comment by Diggsey** [comment]
Not sure why, but this simulator produces random results for my fire script. The other simulators work fine, eg. https://github.com/standupmaths/xmastree2020/pull/5

**Comment by Valtay** [comment]
> Hi, I've been working on something similar - but wanted a fully web-based way for users to edit things (similar to jsfiddle) and found trinket.io.

Hi, mreithub, I've adapted the example to your code, and tried to allow for both hardware and simulation target. I'm really unsure as to whether I got the front/back right. 
https://trinket.io/python/01af695133

**Pull request closed without merging**
