### PR TITLE
2 old school demo effects

### PR DESCRIPTION
**Pull request by Godzil**
3D Plasma and 3D Fire.

My simulator being dumb at the moment it is really hard to see how plasma would render on a real 3D Christmas tree and would probably need a lot of tweaks.

I think 3D fire do works fine, probably would need some tweaks to run properly on the real tree.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @Godzil! Matt asked if I could help with maintaining this repository, so I've been thinking about how best to do that. I've decided to create an examples folder where we can add contributions like this one - you can find some more information in the README.

Would you be up for updating your PR, to move both effects in to the examples folder and remove the empty simulator file? These both seem like nice effects so it would be great to get them merged.

Of course, I understand if you don't have the time to update this and would rather close the PR for now.

**Comment by Godzil** [comment]
Sure no worries, not like a difficult change to do!

**Comment by Godzil** [comment]
I think the changes I made should do it? Please tell me if you see anything are not correct.

I removed the empty sim file (not sure why it was on that branch, must have added it by mistake) also removed some of the code that was referring to it.

**Comment by oliverdunk** [comment]
Looks great, thanks! I'll get this merged. Matt knows about the code here (and that I'm merging some PRs), so if they decide to run some more on the tree they'll know where to look.

**Comment by Godzil** [comment]
👍

**Pull request merged**
