### PR TITLE
Conway's Tree of Life

### PR DESCRIPTION
**Pull request by kevroy314**
Not sure how you want folks to submit animations, but I spent a little bit tonight making Conway's Game of Life on your tree. It was really fun - thank you for setting it up!

Side note: I think this could be made a LOT prettier by fading the LEDs out rather than just turning them off and on, but I didn't have time to implement that visual feature. There are also probably other Cellular Automata rules that will look prettier on a tree. Should be easy enough to add whatever rule you like to the `transition_function`.

Another fun thing you could try is initializing the states to try to create gliders. Might be impossible given it's being computed on a graph, not a grid, though.

### CODE REVIEW

**Comment by nkrasner** [comment]
In the youtube description, he said to email it to him at matt@standupmaths.com
I was just about to attempt this but you beat me to the punch, nice job!

**Comment by kevroy314** [comment]
> In the youtube description, he said to email it to him at [matt@standupmaths.com](mailto:matt@standupmaths.com)
> I was just about to attempt this but you beat me to the punch, nice job!

Thanks! Totally missed the email request. 

If you want to pull this and put in a more fun rule, starting state, or color map, I think it could really be improved a lot! Also, I think treating it as a conical surface instead of this KNN approach might be more visually pleasing (though you have to deal with the "inside" LEDs then.

**Comment by oliverdunk** [comment]
Hey @kevroy314! Love the idea of doing the Game of Life.

Matt asked if I could help with maintaining this repository, so I've been thinking about how best to do that. I've decided to create an examples folder where we can add contributions like this one - you can find some more information in the [README](https://github.com/standupmaths/xmastree2020).

Would you be up for moving your effect in to to a single file, and updating this PR to add it to the examples folder? Alternatively, you could add a link to your repository in the "Further Work" section of this one.

Of course, I understand if you don't have the time to update this and would rather close the PR for now.

**Comment by kevroy314** [comment]
> Hey @kevroy314! Love the idea of doing the Game of Life.
> 
> Matt asked if I could help with maintaining this repository, so I've been thinking about how best to do that. I've decided to create an examples folder where we can add contributions like this one - you can find some more information in the [README](https://github.com/standupmaths/xmastree2020).
> 
> Would you be up for moving your effect in to to a single file, and updating this PR to add it to the examples folder? Alternatively, you could add a link to your repository in the "Further Work" section of this one.
> 
> Of course, I understand if you don't have the time to update this and would rather close the PR for now.

Hey @oliverdunk , sure, it'd be happy to. Might take me a few days to get to it. 

Question about the single-file thing. I can do that for the actual LED code, but I left the visualization/simulation code in there so people could see what it looked like without running it. Is there a place in the repo you'd want that code? Or would you rather stick to screenshots/gifs hosted elsewhere and linked to in the README?

**Comment by oliverdunk** [comment]
@kevroy314 I definitely like the idea of a simulator, but I don't think it makes sense to have more than one. With that in mind, I picked out https://github.com/standupmaths/xmastree2020/pull/5 and am waiting to hear back from the author in hopes of merging it 🤞 

I hope you understand - I had to pick one and I chose that one for it's simplicity. Nothing personal!

As far as your screenshots etc., perhaps provide a comment in the top of your Python file with links to any extra resources you want to share? Definitely cool that you put those together so would be a shame to lose them :)

**Comment by kevroy314** [comment]
Unfortunately, I don't think I'm going to have time to merge this - going to close for now.

**Pull request closed without merging**
