### PR TITLE
Fire animation

### PR DESCRIPTION
**Pull request by Diggsey**
I wasn't able to test this for real, so I hope it works...

The animation it produces should look something like this (except that it will continue smoothly instead of stuttering after each loop...):

The animation is designed to tile horizontally, so I map it onto the tree by taking the angle of an LED from the central axis and using that as the X coordinate in the animation frame.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @Diggsey! Matt asked if I could help with maintaining this repository, so I've been thinking about how best to do that. I've decided to create an examples folder where we can add contributions like this one - you can find some more information in the [README](https://github.com/standupmaths/xmastree2020).

Would you be up for updating this PR to move your effect in to the examples folder? Fire seems like a really nice one to have.

Of course, I understand if you don't have the time to update this and would rather close the PR for now.

**Comment by Diggsey** [comment]
@oliverdunk Updated

**Comment by oliverdunk** [comment]
> @oliverdunk Updated

Amazing, thanks! Would you be able to remove the gif too? I was going to mention that in my original comment but I think I forgot 😅

**Comment by Diggsey** [comment]
Done

**Comment by oliverdunk** [comment]
Thanks again! I'll get this merged as the first addition to the original code 🎉 

By the way - I let Matt know about all of the code here, including yours. I can't promise he'll be able to run it, but even with this merged, he's still aware of its existence.

**Pull request merged**
